-- =====================================================================
-- Portfolio 1 : Database Design and Modelling
-- Case study  : MafixxStores (e-commerce platform, synthetic data)
-- Run inside database "mafixx" :  psql -U postgres -d mafixx -f 01_schema.sql
-- =====================================================================
DROP TABLE IF EXISTS stock_log, deliveries, payments, order_items, orders, products, suppliers, categories, customers CASCADE;

CREATE TABLE customers (
    customer_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(150) NOT NULL UNIQUE,
    phone        VARCHAR(20),
    city         VARCHAR(60)  NOT NULL,
    state        VARCHAR(60)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE categories (
    category_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE suppliers (
    supplier_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name  VARCHAR(120) NOT NULL UNIQUE,
    city           VARCHAR(60)
);

CREATE TABLE products (
    product_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(20)  NOT NULL UNIQUE,
    product_name  VARCHAR(150) NOT NULL,
    category_id   INT NOT NULL REFERENCES categories(category_id),
    supplier_id   INT NOT NULL REFERENCES suppliers(supplier_id),
    unit_price    NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
    stock_qty     INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),   -- prevents negative stock
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    order_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   INT NOT NULL REFERENCES customers(customer_id),
    order_date    TIMESTAMP NOT NULL DEFAULT now(),
    status        VARCHAR(20) NOT NULL DEFAULT 'Pending'
                  CHECK (status IN ('Pending','Paid','Shipped','Delivered','Cancelled')),
    total_amount  NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0)
);

-- Junction table: resolves the many-to-many between orders and products
CREATE TABLE order_items (
    order_id    INT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id  INT NOT NULL REFERENCES products(product_id),
    quantity    INT NOT NULL CHECK (quantity > 0),
    unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),   -- price AT THE TIME of purchase
    PRIMARY KEY (order_id, product_id)                            -- composite key
);

CREATE TABLE payments (
    payment_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE,  -- 1 order : 1 payment
    amount          NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
    method          VARCHAR(30) NOT NULL CHECK (method IN ('Card','Bank Transfer','USSD','Wallet','Pay on Delivery')),
    payment_status  VARCHAR(20) NOT NULL CHECK (payment_status IN ('Pending','Successful','Failed','Refunded')),
    paid_at         TIMESTAMP
);

CREATE TABLE deliveries (
    delivery_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         INT NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE, -- 1 order : 0..1 delivery
    courier          VARCHAR(60) NOT NULL,
    delivery_status  VARCHAR(20) NOT NULL CHECK (delivery_status IN ('In Transit','Delivered')),
    shipped_at       TIMESTAMP,
    delivered_at     TIMESTAMP,
    delivery_city    VARCHAR(60),
    CHECK (delivered_at IS NULL OR delivered_at >= shipped_at)
);

-- Audit table used in Portfolio 3 (transactions)
CREATE TABLE stock_log (
    log_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  INT NOT NULL REFERENCES products(product_id),
    change_qty  INT NOT NULL,
    reason      VARCHAR(100) NOT NULL,
    logged_at   TIMESTAMP NOT NULL DEFAULT now()
);
